server:
  http:
    addr: 0.0.0.0:8085
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9085
    timeout: 1s

database:
  host: localhost
  port: 15432
  user: postgres
  password: postgres
  dbname: rbac
  sslmode: disable
  max_open_conns: 25
  max_idle_conns: 10
  conn_max_lifetime: 5m

kessel:
  relations_api:
    host: localhost
    port: 9000
    tls_enabled: false
    timeout: 5s

app:
  name: mini-rbac-go
  version: v0.1.0
  env: development
  replication_enabled: true
